<!-- <div class="jumbotron"> -->
<!--     <h1> -->
    <?php  // echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?>
<!--     </h1> -->
<!--     <p> -->
    <?php // echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?>
<!--     </p> -->
<!--     <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"> -->
    	<?php // echo $this->translate('Fork Zend Framework 2 on GitHub') ?> 
<!--     	&raquo; -->
<!--     	</a></p> -->
<!-- </div> -->

<!-- <div class="row"> -->

<!--     <div class="col-md-4"> -->
<!--         <div class="panel panel-default"> -->
<!--             <div class="panel-heading"> -->
<!--                 <h3 class="panel-title"> -->
                <?php // echo $this->translate('Follow Development') ?>
<!--                 </h3> -->
<!--             </div> -->
<!--             <div class="panel-body"> -->
<!--                 <p> -->
                <?php // echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?>
<!--                 </p> -->
<!--                 <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"> -->
                <?php // echo $this->translate('ZF2 Development Portal') ?> 
<!--                 &raquo;</a></p> -->
<!--             </div> -->
<!--         </div> -->
<!--     </div> -->

<!--     <div class="col-md-4"> -->
<!--         <div class="panel panel-default"> -->
<!--             <div class="panel-heading"> -->
<!--                 <h3 class="panel-title"> -->
                <?php // echo $this->translate('Discover Modules') ?>
<!--                 </h3> -->
<!--             </div> -->
<!--             <div class="panel-body"> -->
<!--                 <p> -->
                <?php // echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?>
<!--                 </p> -->
<!--                 <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"> -->
                <?php // echo $this->translate('Explore ZF2 Modules') ?> 
<!--                 &raquo;</a></p> -->
<!--             </div> -->
<!--         </div> -->
<!--     </div> -->

<!--     <div class="col-md-4"> -->
<!--         <div class="panel panel-default"> -->
<!--             <div class="panel-heading"> -->
<!--                 <h3 class="panel-title"> -->
                <?php // echo $this->translate('Help &amp; Support') ?>
<!--                 </h3> -->
<!--             </div> -->
<!--             <div class="panel-body"> -->
<!--                 <p> -->
                <?php // echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?>
<!--                 </p> -->
<!--                 <p> -->
<!--                 <a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"> -->
                <?php // echo $this->translate('Ping us on IRC') ?> 
<!--                 &raquo;</a></p> -->
<!--             </div> -->
<!--         </div> -->
<!--     </div> -->
<!-- </div> -->
 
<?php 

$script ='<script type="javascript/text">
            $(document).ready(function()
            {
        
                    console.log("kkkkk");
                $("#bill").click(function()
                {
                    console.log("kkkkk");
                    $("#gamecontent").innerHtml("lllll");
                });
            });
          </script>';

$tab = '<table border=1>
            <tr>
                <td style="cursor: pointer" id="bill"> Billard</td>
                <td rowspan=3>
                    <div id="gamecontent" align="center">
        
                    </div>
                </td>
            </tr>
            <tr>
                <td>Super Mario</td>
               
            </tr>
            <tr>
                <td>tttt</td>
              
            </tr>
        </table>';
        
echo $tab;
echo $script;

echo '  <div align="center">
            <object width="500" height="400">
                <param name="movie" value="http://www.myspiele.net/content/games/billiard.swf">
                    <param name="quality" value="high">
                    <embed src="http://www.myspiele.net/content/games/billiard.swf" 
                           quality="high" 
                           width="500" 
                           height="400" 
                           type="application/x-shockwave-flash" 
                           pluginspage= "http://www.macromedia.com/go/getflashplayer">
                </embed>
            </object>
        <!--
            <a href="http://www.myspiele.net">
                <strong>my Spiele</strong>
            </a>
        -->
        </div>
        <br>';
        
echo '  <div align="center">
            <object width="500" height="400">
                <param name="movie" value="http://www.myspiele.net/content/games/marios-abenteuer-2.swf">
                <param name="quality" value="high">
                    <embed src="http://www.myspiele.net/content/games/marios-abenteuer-2.swf" 
                           quality="high" 
                           width="500" 
                           height="400" 
                           type="application/x-shockwave-flash" 
                           pluginspage= "http://www.macromedia.com/go/getflashplayer">
                    </embed>
            </object>
        </div>
<br>
        <a href="http://www.myspiele.net" target="_blank">
                <img src="http://www.myspiele.net/templates/spiele/images/spiele.png"  
                     border="0" height="90" width="188">
            </a>


';



$string = '<div style="margin-top:20%; width: 80%; height: 90%; position: fix; font-size: 28pt; font-weight:bold; color: red;" >';

$string .= '<center>';
//             <div>If you want to hack this web site, go play with your penis better ;) </div>
//         <br><br>
//             <div> Son of the bitch</div>
$string .= '<img src="https://www.colourbox.de/preview/10018244-funny-cartoon-donkey.jpg" > ';
$string .= '</center>';
$string .='</div>';

echo $string;

die;
?>
